// Package legal hosts the R166 LIABILITY_FOOTER_CONST for cohort-walker.
//
// R166 LIABILITY-FOOTER-CONST (PROMOTED 2026-05-27, batch 3, 10/3 strict)
// requires every cohort flagship to ship a literal-string liability footer
// constant whose value is byte-identical with the cohort canonical shape
// across substrates. This file is cohort-walker's contribution.
//
// The footer is appended to any user-facing drift report so that operators
// and regulators reading the report cannot mistake an automated drift scan
// for an authoritative compliance verdict. The footer is intentionally
// blunt: cohort-walker reports byte-equality and presence; it does not
// adjudicate intent.
package legal

// LiabilityFooter is the canonical liability disclaimer printed on every
// human-readable drift report. The literal constant participates in the
// R166 cohort by shape and substring family.
const LiabilityFooter = `[NOT LEGAL ADVICE — TOOL OUTPUT FOR INFORMATIONAL USE ONLY]

This drift report is generated by cohort-walker, an automated cross-cohort
scanner. It reports byte-equality of cryptographic anchors (KAT-1), wire-
format prefix presence, and module declarations. It does NOT adjudicate
whether a flagship is fit for any regulated purpose, nor whether its
absence from a cohort row means the flagship is non-compliant. A failing
row signals a difference worth a human review; it does not signal fraud,
negligence, or breach.

Operators MUST treat each FAIL row as a prompt to investigate, not as a
finding of fault. Where this report is presented to a regulator, a third-
party audit, or a court, a qualified human reviewer MUST sign off on the
underlying claim. cohort-walker carries no warranty under the Apache-2.0
licence; see LICENSE for the full disclaimer.
`

// Tag exposes the R166-class machine-readable tag that downstream
// regulator automation grep for.
const Tag = "R166_LIABILITY_FOOTER_CONST"
